/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Type of banking account.
 */
export enum AccountType {
    Checking = "CHECKING",
    Saving = "SAVING",
    CorporateChecking = "CORPORATE_CHECKING",
}
