/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../../sdk/types";
import { Address } from "./address";
import { Phone } from "./phone";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Card owner properties
 */
export class AccountHolderOutput extends SpeakeasyBase {
    /**
     * Designates the century, year, month and day that a merchant's customer profile has been first defined.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "consumerIdCreationDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    consumerIdCreationDate?: RFCDate;
}

/**
 * Card owner properties
 */
export class AccountHolder extends SpeakeasyBase {
    /**
     * IP Address from where the transaction is originating
     */
    @SpeakeasyMetadata()
    @Expose({ name: "IPAddress" })
    ipAddress?: string;

    /**
     * Address Object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billingAddress" })
    @Type(() => Address)
    billingAddress?: Address;

    /**
     * Designates the century, year, month and day that a merchant's customer profile has been first defined.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "consumerIdCreationDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    consumerIdCreationDate?: RFCDate;

    /**
     * Optional value for merchants to provide for a transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * Name of accountholder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fullName" })
    fullName?: string;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mobile" })
    @Type(() => Phone)
    mobile?: Phone;

    /**
     * An identifier for the consumer or business assigned by a government authority.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nationalId" })
    nationalId?: string;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    @Type(() => Phone)
    phone?: Phone;

    /**
     * Merchant defined identifier for a consumer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "referenceId" })
    referenceId?: string;
}
