/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The label given to indicate if the account number is stored, not stored, or is going to be stored by a merchant. Valid values: STORED NOT_STORED TO_BE_STORED
 */
export enum AccountOnFile {
    NotStored = "NOT_STORED",
    Stored = "STORED",
    ToBeStored = "TO_BE_STORED",
}
