/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../../sdk/types";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Card owner properties
 */
export class AccountHolderOutput extends SpeakeasyBase {
    /**
     * Designates the century, year, month and day that a merchant's customer profile has been first defined.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "consumerIdCreationDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    consumerIdCreationDate?: RFCDate;
}
