/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { Address } from "./address";
import { Phone } from "./phone";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Information about the card Account Holder for which fraud checking is performed.
 */
export class AccountHolderInformationInput extends SpeakeasyBase {
    /**
     * Address Object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billingAddress" })
    @Type(() => Address)
    billingAddress?: Address;

    /**
     * Specifies the year month and day on which the individual was born.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "birthDate" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    birthDate?: RFCDate;

    /**
     * Designates the century, year, month and day that a merchant's customer profile has been first defined.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "consumerIdCreationDate" })
    consumerIdCreationDate?: string;

    /**
     * A unique string of numbers separated by periods that identifies each device using the Internet Protocol (IP) to communicate over a network.  An IP address is assigned to every single computer, printer, switch, router or any other device that is part of a TCP/IP-based network which allows users to send and receive data. The numerals in an IP address are divided into two parts:  1) The network part specifies which networks this address belongs to and 2) The host part further pinpoints the exact location. In this context, this is the IP address of the devices associated with the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceIPAddress" })
    deviceIPAddress?: string;

    /**
     * A unique identifier assigned by a government agency that is not used by a Tax Authority to administer tax laws or by another government body to administer social and government programs. It may be used in conjunction with the party non tax government issued identifier type code. Examples include Driver's License number, green card id, and Passport number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "driverLicenseNumber" })
    driverLicenseNumber?: string;

    /**
     * Optional value for merchants to provide for a transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * Name of accountholder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fullName" })
    fullName?: string;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    @Type(() => Phone)
    phone?: Phone;

    /**
     * Merchant defined identifier for a consumer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "referenceId" })
    referenceId?: string;
}
