/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Returned when more information about authentication is received from the  network
 */
export class AuthenticationValueResponse extends SpeakeasyBase {
    /**
     * 3-D Secure authentication response code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * 3-D Secure authentication response message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}
