/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Card name
 */
export enum CardTypeName {
    Visa = "VISA",
    Mastercard = "MASTERCARD",
    AmericanExpress = "AMERICAN_EXPRESS",
    Hipercard = "HIPERCARD",
    Elo = "ELO",
    Discover = "DISCOVER",
    Jcb = "JCB",
    DinersClub = "DINERS_CLUB",
    ChinaUnionPay = "CHINA_UNION_PAY",
    ChasenetCredit = "CHASENET_CREDIT",
    ChasenetSignatureDebit = "CHASENET_SIGNATURE_DEBIT",
    Oxxo = "OXXO",
    InternationalMaestro = "INTERNATIONAL_MAESTRO",
}
