/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PaymentBrandCardTypeCode } from "./paymentbrandcardtypecode";
import { Expose } from "class-transformer";

export enum CardTypeIndicatorsCardProductTypes {
    Commercial = "COMMERCIAL",
    Payroll = "PAYROLL",
    Healthcare = "HEALTHCARE",
    AffluentCategory = "AFFLUENT_CATEGORY",
    SignatureDebit = "SIGNATURE_DEBIT",
    PinlessDebit = "PINLESS_DEBIT",
    PrepaidReloadable = "PREPAID_RELOADABLE",
}

/**
 * The card type indicators provide additional information about the card. For example, if the card is a prepaid card and thus less likely to         support recurring payments or if the card is a healthcare or commercial  card.
 */
export class CardTypeIndicators extends SpeakeasyBase {
    /**
     * The label given to the issuer of a card-based payment account. The term "issuer" may refer to either the payment brand itself, as for the American Express and Discover payment brands, or the issuer will be a financial institution authorized to issue cards with the payment brand logo, as is the case for Visa and MasterCard.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardIssuerName" })
    cardIssuerName?: string;

    /**
     * Lable given to the primary processing network on which the account can make credit transactions. It also specifies the product types that VISA and MasterCard use to classify accounts for reporting. Note: There are some codes that are used only by Common Profit Book (CPB). Within the CPB, the existing code is replaced based on information from MasterCard and Visa. Formerly known as Association Product Code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardProductName" })
    cardProductName?: string;

    /**
     * List of card products applicable for the account number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardProductTypes" })
    cardProductTypes?: CardTypeIndicatorsCardProductTypes[];

    /**
     * Codifies a high level classification associated with the card account that could indicate how the issuer account is funded or used, e.g. Debit, Credit, Prepaid, Single Use.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardTypeCategory" })
    cardTypeCategory?: PaymentBrandCardTypeCode;

    /**
     * Whether the card is regulated as per the Durbin Amendment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isDurbinRegulated" })
    isDurbinRegulated?: boolean;

    /**
     * Whether the card is eligible for Level 3 fields
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isLevel3Eligible" })
    isLevel3Eligible?: boolean;

    /**
     * Uniquely represents a firm-recognized geopolitical area, including the ISO 3166 alpha 2-character country codes and other firm-created country codes. In this context, this is the ISO alphabetic country code, e.g. USA = United States
     */
    @SpeakeasyMetadata()
    @Expose({ name: "issuanceCountryCode" })
    issuanceCountryCode?: string;
}
