/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Abbreviation of card name
 */
export enum CardType {
    Vi = "VI",
    Mc = "MC",
    Ax = "AX",
    Hc = "HC",
    Eo = "EO",
    Di = "DI",
    Jc = "JC",
    Dc = "DC",
    Cc = "CC",
    Cz = "CZ",
    Cr = "CR",
    Ox = "OX",
    Im = "IM",
}
