/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Expiration date
 */
export class Expiry extends SpeakeasyBase {
    /**
     * The month of the expiration date
     */
    @SpeakeasyMetadata()
    @Expose({ name: "month" })
    month: number;

    /**
     * The year of the expiration date
     */
    @SpeakeasyMetadata()
    @Expose({ name: "year" })
    year: number;
}
