/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Phone } from "./phone";
import { Expose, Type } from "class-transformer";

/**
 * Ship To Information used for fraud checking services.
 */
export class FraudShipTo extends SpeakeasyBase {
    /**
     * That part of an individual's full name considered a personal name or given name and generally positioned before the last name or family name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "firstName" })
    firstName?: string;

    /**
     * Name of accountholder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fullName" })
    fullName?: string;

    /**
     * That part of an individual?s name generally placed at the end of the given name. The last name is also known as the surname or family name. (Note: name conventions may be different based on practices in different countries. Some countries use two or more last names; in other countries, the family name is placed before a person?s given name; in some countries, it is common for people to have only one name or a mononym.)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastName" })
    lastName?: string;

    /**
     * That part of an individual's name generally positioned between the first and family names, as a second given name or a maternal surname. (NOTE: in some instances, an individual may have multiple middle names)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "middleName" })
    middleName?: string;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    @Type(() => Phone)
    phone?: Phone;

    /**
     * Address Object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingAddress" })
    @Type(() => Address)
    shippingAddress?: Address;

    /**
     * Description of shipping or delivery method
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingDescription" })
    shippingDescription?: string;
}
