/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountHolderInformationInput } from "./accountholderinformation";
import { Currency } from "./currency";
import { FraudCheckPaymentMethodTypeInput } from "./fraudcheckpaymentmethodtype";
import { FraudScore } from "./fraudscore";
import { FraudShipTo } from "./fraudshipto";
import { MerchantInput } from "./merchant";
import { Expose, Type } from "class-transformer";

/**
 * Object for passing fraud check request parameters
 */
export class FraudCheckRequestInput extends SpeakeasyBase {
    /**
     * Information about the card Account Holder for which fraud checking is performed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "accountHolder" })
    @Type(() => AccountHolderInformationInput)
    accountHolder?: AccountHolderInformationInput;

    /**
     * Specifies the monetary value of the transaction performed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    /**
     * Describes the currency type of the transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: Currency;

    /**
     * Object for Fraud Score Information
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudScore" })
    @Type(() => FraudScore)
    fraudScore?: FraudScore;

    /**
     * Information about the merchant
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchant" })
    @Type(() => MerchantInput)
    merchant?: MerchantInput;

    /**
     * Object with information for Payment Method Type for  Fraud Check
     */
    @SpeakeasyMetadata()
    @Expose({ name: "paymentMethodType" })
    @Type(() => FraudCheckPaymentMethodTypeInput)
    paymentMethodType: FraudCheckPaymentMethodTypeInput;

    /**
     * Ship To Information used for fraud checking services.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipTo" })
    @Type(() => FraudShipTo)
    shipTo?: FraudShipTo;
}
