/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A list of informational messages
 */
export class Information extends SpeakeasyBase {
    /**
     * Codifies the instruction provided in the application
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Long explanation of the instruction provided in the application
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}
