/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the initiator of the transaction for the stored credential framework (MIT/CIT)
 */
export enum InitiatorType {
    Cardholder = "CARDHOLDER",
    Merchant = "MERCHANT",
}
