/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Object containing information in the file
 */
export class Installment extends SpeakeasyBase {
    /**
     * Measures the number of recurring payments expected to be made by the customer over a scheduled period of time in order to pay the total amount charged.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "installmentCount" })
    installmentCount?: number;

    /**
     * Specifies the number of month an installment payment can be postponed or suspended.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numberOfDeferrals" })
    numberOfDeferrals?: number;

    /**
     * Contains the payment plan identifier.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "planId" })
    planId?: string;
}
