/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LineItem } from "./lineitem";
import { TransactionAdvice } from "./transactionadvice";
import { Expose, Type } from "class-transformer";

/**
 * Level 3 data provides commercial shoppers with additional information about purchases on their card statements.
 */
export class Level3 extends SpeakeasyBase {
    /**
     * The amount added to the transaction for taxes.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "alternateTaxAmount" })
    alternateTaxAmount?: number;

    /**
     * Specifies the monetary value for an additional tax levied or tariff charged against the purchase of goods or services imported from another country. Taxes or tariffs (duties) are also charged for some forms of exports. The customs authorities for a country are usually the taxing body, and duties are enforceable by law. Synonyms include but are not limited to: tax, toll, excise, levy, charge, rate, fee, countervail, customs and price list.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dutyAmount" })
    dutyAmount?: number;

    /**
     * List Of line Items
     */
    @SpeakeasyMetadata({ elemType: LineItem })
    @Expose({ name: "lineItems" })
    @Type(() => LineItem)
    lineItems?: LineItem[];

    /**
     * Indicates how the merchant is managing discounts.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "orderDiscountTreatmentCode" })
    orderDiscountTreatmentCode?: string;

    /**
     * An identifier assigned by a government agency that is used by a Tax Authority to administer tax laws or by another government body to administer social and government programs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "partyTaxGovernmentIssuedIdentifier" })
    partyTaxGovernmentIssuedIdentifier?: string;

    /**
     * The portion of a party?s address that is the encoded representation of a geographic area to facilitate mail delivery services.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipFromAddressPostalCode" })
    shipFromAddressPostalCode?: string;

    /**
     * A code that identifies the Country, a Geographic Area, that is recognized as an independent political unit in world affairs. Note: This data element is a child of the Country Code CDE and valid values are based on ISO standards.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipToAddressCountryCode" })
    shipToAddressCountryCode?: string;

    /**
     * The portion of a party?s address that is the encoded representation of a geographic area to facilitate mail delivery services.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipToAddressPostalCode" })
    shipToAddressPostalCode?: string;

    /**
     * Specifies the monetary value of the Value Added Tax (VAT) charged for either a line item or an entire transaction. VAT is a consumption tax levied on the sale of goods and services (a.k.a. Goods and Services Tax (GST)). VAT is an indirect tax, in that the tax is collected from someone other than the person who actually bears the cost of the tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingValueAddedTaxAmount" })
    shippingValueAddedTaxAmount?: number;

    /**
     * Specifies the fixed ratio applied to the transaction for Value Added Tax for a line item or an entire transaction. VAT is a consumption tax levied on the sale of goods and services (a.k.a. Goods and Services Tax (GST)). VAT is an indirect tax, in that the tax is collected from someone other than the person who actually bears the cost of the tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingValueAddedTaxPercent" })
    shippingValueAddedTaxPercent?: string;

    /**
     * Specifies the monetary value to be paid for the postage and related transportation to get a package from the shipping carrier to the consumer for all items purchased.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalShippingAmount" })
    totalShippingAmount?: number;

    /**
     * Specifies the monetary value to which the merchant applied a reduction (e.g., percentage or fixed amount) to a single line item of the purchase, the total purchase amount, or the tax portion of the transaction. If the reduction is for the taxable portion of the transaction, then the monetary value of the tax levied becomes a fixed purchase price reduction for the total transaction and the purchaser; yet the tax is still levied and collected against the reduced purchase amount and reported to the taxing body.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalTransactionDiscountAmount" })
    totalTransactionDiscountAmount?: number;

    /**
     * List of transaction advices from American Express
     */
    @SpeakeasyMetadata({ elemType: TransactionAdvice })
    @Expose({ name: "transactionAdvices" })
    @Type(() => TransactionAdvice)
    transactionAdvices?: TransactionAdvice[];

    /**
     * Specifies the monetary value of the Value Added Tax (VAT) charged for either a line item or an entire transaction. VAT is a consumption tax levied on the sale of goods and services (a.k.a. Goods and Services Tax (GST)). VAT is an indirect tax, in that the tax is collected from someone other than the person who actually bears the cost of the tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "valueAddedTaxAmount" })
    valueAddedTaxAmount?: number;

    /**
     * Identifies the additional subelement used to identify the value-added tax (VAT) invoice or tax receipt.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "valueAddedTaxInvoiceReferenceNumber" })
    valueAddedTaxInvoiceReferenceNumber?: string;

    /**
     * Specifies the fixed ratio applied to the transaction for Value Added Tax for a line item or an entire transaction. VAT is a consumption tax levied on the sale of goods and services (a.k.a. Goods and Services Tax (GST)). VAT is an indirect tax, in that the tax is collected from someone other than the person who actually bears the cost of the tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "valueAddedTaxPercent" })
    valueAddedTaxPercent?: string;
}
