/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LineItemTax } from "./lineitemtax";
import { Expose, Type } from "class-transformer";

/**
 * Line Item data within the Level 3
 */
export class LineItem extends SpeakeasyBase {
    /**
     * Codifies the category the item being purchased belongs in a standardized commodity group as defined by the card acceptor.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "itemComodityCode" })
    itemComodityCode?: string;

    /**
     * Provides detailed information regarding specific goods or services that have been procured and for which payment has been requested.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemDescriptionText" })
    lineItemDescriptionText?: string;

    /**
     * codifies type of line item detail record.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemDetailCode" })
    lineItemDetailCode?: string;

    /**
     * Indicates whether the amount is discounted.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemDiscountIndicator" })
    lineItemDiscountIndicator?: boolean;

    /**
     * Indicates how the merchant is handling discount at line item level. Valid value:  0 ? No line level discount  1 ? Tax calculated on post-discount line item total  2 ? Tax calculated on pre-discount line item total
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemDiscountTreatmentCode" })
    lineItemDiscountTreatmentCode?: string;

    /**
     * Indicates whether tax amount is included in item amount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemTaxIndicator" })
    lineItemTaxIndicator?: boolean;

    /**
     * List Of line Items Tax Information
     */
    @SpeakeasyMetadata({ elemType: LineItemTax })
    @Expose({ name: "lineItemTaxes" })
    @Type(() => LineItemTax)
    lineItemTaxes?: LineItemTax[];

    /**
     * Enumerates the volume (quantity) of each individual product type included in the transaction. The quantity, unit of measure and the line item price is used to calculate the aggregated purchase amount for each line item. In some cases, quantity can include a fraction or decimal places to allow for items such as hours of service provided, or a pound portion of goods.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemUnitQuantity" })
    lineItemUnitQuantity?: string;

    /**
     * Codifies the method used for computing the size, length, magnitude or other form of good, service or other measurement, expressed as a number or measure (e.g., drum, box, tote, bucket) or quantity (e.g., KTM = Kilometer, LBR = pound, MIN = minute). It is used in combination with a Line Item Product Type Count and Line Item Price to calculate the purchase amount for that line item in a transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lineItemUnitofMeasureCode" })
    lineItemUnitofMeasureCode?: string;

    /**
     * A unique merchant assigned identifier for an item or service offered for sale by the Merch
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantProductIdentifier" })
    merchantProductIdentifier?: string;

    /**
     * Specifies the ratio of the reduction amount applied by the merchant (e.g., based on a percentage or fixed amount) to the purchase amount on a transaction. Discount percentages could be calculated at individual line item, or total transaction levels.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "purchaseTransactionDiscountPercent" })
    purchaseTransactionDiscountPercent?: string;

    /**
     * Specifies the monetary value (inclusive of tax) for the price of the product or service multiplied by the quantity of the items purchased recorded in the transaction addendum data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "taxInclusiveLineItemTotalAmount" })
    taxInclusiveLineItemTotalAmount?: number;

    /**
     * Specifies the monetary value to which the merchant applied a reduction (e.g., percentage or fixed amount) to a single line item of the purchase, the total purchase amount, or the tax portion of the transaction. If the reduction is for the taxable portion of the transaction, then the monetary value of the tax levied becomes a fixed purchase price reduction for the total transaction and the purchaser; yet the tax is still levied and collected against the reduced purchase amount and reported to the taxing body.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transactionDiscountAmount" })
    transactionDiscountAmount?: number;

    /**
     * Specifies the monetary value of the per-item cost of a good or service.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unitPriceAmount" })
    unitPriceAmount?: number;
}
