/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains information related to the merchant software
 */
export class MerchantSoftware extends SpeakeasyBase {
    /**
     * The label given to a formally organized or incorporated firm known as a legal entity. In this context, this is the company a merchant is sourcing its payment processing software from.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "companyName" })
    companyName: string;

    /**
     * The name of the product used for marketing purposes from a customer perspective. I. e. what the customer would recognize.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productName" })
    productName: string;

    /**
     * Designates the unique state of computer software as it is developed and released. The version identifier can be a word, or a number, or both.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
