/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Label given to a merchant client of the Firm's medium for reaching its customers and facilitating and/or performing sales of its merchandise or services.
 */
export enum MerchantSalesChannelName {
    MailOrderTelephoneOrder = "MAIL_ORDER_TELEPHONE_ORDER",
    Internet = "INTERNET",
    InteractiveVoiceResponse = "INTERACTIVE_VOICE_RESPONSE",
}
