/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Codifies the routing model used to route the transaction as preferred by merchant.
 */
export enum MerchantPreferredRouting {
    Pinless = "PINLESS",
    Credit = "CREDIT",
}
