/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MerchantSoftware } from "./merchantsoftware";
import { SoftMerchant, SoftMerchantOutput } from "./softmerchant";
import { Expose, Type } from "class-transformer";

/**
 * Information about the merchant
 */
export class MerchantOutput extends SpeakeasyBase {
    /**
     * MCC or Merchant Category Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantCategoryCode" })
    merchantCategoryCode?: string;

    /**
     * Identifier for the merchant account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantId" })
    merchantId?: string;

    /**
     * A reference to a web resource on the internet specifying its location on a computer network and a mechanism for retrieving. This is a pointer to a location containing the merchant's registered trademark  (e.g. for the Firm, the stylized CHASE followed by the Octagon).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantLogoUrl" })
    merchantLogoUrl?: string;

    /**
     * Contains information related to the merchant software
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantSoftware" })
    @Type(() => MerchantSoftware)
    merchantSoftware: MerchantSoftware;

    /**
     * Soft merchant information is passed to the card association along with the transaction. This soft merchant information may also be used for cases where smaller businesses or franchise outlets are making a sale in which a merchant aggregator or payment facilitatorprocesses the payment transaction on their behalf.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "softMerchant" })
    @Type(() => SoftMerchantOutput)
    softMerchant?: SoftMerchantOutput;
}

/**
 * Information about the merchant
 */
export class Merchant extends SpeakeasyBase {
    /**
     * MCC or Merchant Category Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantCategoryCode" })
    merchantCategoryCode?: string;

    /**
     * A reference to a web resource on the internet specifying its location on a computer network and a mechanism for retrieving. This is a pointer to a location containing the merchant's registered trademark  (e.g. for the Firm, the stylized CHASE followed by the Octagon).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantLogoUrl" })
    merchantLogoUrl?: string;

    /**
     * Contains information related to the merchant software
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchantSoftware" })
    @Type(() => MerchantSoftware)
    merchantSoftware: MerchantSoftware;

    /**
     * Soft merchant information is passed to the card association along with the transaction. This soft merchant information may also be used for cases where smaller businesses or franchise outlets are making a sale in which a merchant aggregator or payment facilitatorprocesses the payment transaction on their behalf.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "softMerchant" })
    @Type(() => SoftMerchant)
    softMerchant?: SoftMerchant;
}
