/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Split Shipment Information
 */
export class MultiCapture extends SpeakeasyBase {
    /**
     * Indicates if it is the final shipment associated with a single authorization.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isFinalCapture" })
    isFinalCapture?: boolean;

    /**
     * Enumerates the quantity of records in a data object that is processed or transmitted. In this context, this is the the total number of expected shipments associated with a single authorization.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "multiCaptureRecordCount" })
    multiCaptureRecordCount?: number;

    /**
     * Identifies the number indicating the location of this record in the sorting sequence of the specified data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "multiCaptureSequenceNumber" })
    multiCaptureSequenceNumber?: string;
}
