/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardInput } from "./card";
import { Expose, Type } from "class-transformer";

/**
 * Multi Capture Payment Method Type contains all the payment method code supported for multi capture payment processing capability
 */
export class MultiCapturePaymentMethodTypeInput extends SpeakeasyBase {
    /**
     * Card payment instrument
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => CardInput)
    card?: CardInput;
}
