/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AdditionalData } from "./additionaldata";
import { NetworkResponseAccountUpdater } from "./networkresponseaccountupdater";
import { Expose, Type } from "class-transformer";

/**
 * Indicates if address provided matches the billing address
 */
export enum AddressVerificationResult {
    AddressMatch = "ADDRESS_MATCH",
    AddressPostalcodeMatch = "ADDRESS_POSTALCODE_MATCH",
    NameAddressMatch = "NAME_ADDRESS_MATCH",
    NameMatch = "NAME_MATCH",
    NamePostalcodeMatch = "NAME_POSTALCODE_MATCH",
    NoMatch = "NO_MATCH",
    NotAvailable = "NOT_AVAILABLE",
    NotRequested = "NOT_REQUESTED",
    NotVerified = "NOT_VERIFIED",
    PostalcodeMatch = "POSTALCODE_MATCH",
    ServiceNotAvailableRetry = "SERVICE_NOT_AVAILABLE_RETRY",
    ServiceNotSupported = "SERVICE_NOT_SUPPORTED",
}

/**
 * Indicates if the card verification values (CVV/CV2) matches
 */
export enum CardVerificationResult {
    Match = "MATCH",
    NotPresent = "NOT_PRESENT",
    NotProcessed = "NOT_PROCESSED",
    NotSupported = "NOT_SUPPORTED",
    NoMatch = "NO_MATCH",
}

/**
 * Provides the textual detail information of the issuer's authorization response code to a merchant when verifying the cardholder's email address to help authenticate transactions and prevent fraud. This is Amex only field.
 */
export enum EmailVerificationResult {
    Match = "MATCH",
    NoMatch = "NO_MATCH",
    NotVerified = "NOT_VERIFIED",
    ServiceNotAvailableRetry = "SERVICE_NOT_AVAILABLE_RETRY",
    ServiceNotSupported = "SERVICE_NOT_SUPPORTED",
}

/**
 * Codifies the issuer's authorization response code to a merchant when verifying the cardholder's billing telephone number to help authenticate transactions and prevent fraud. This is Amex only field.
 */
export enum PhoneVerificationResult {
    Match = "MATCH",
    NoMatch = "NO_MATCH",
    NotVerified = "NOT_VERIFIED",
    ServiceNotAvailableRetry = "SERVICE_NOT_AVAILABLE_RETRY",
    ServiceNotSupported = "SERVICE_NOT_SUPPORTED",
}

/**
 * Response information from payment network
 */
export class NetworkResponse extends SpeakeasyBase {
    /**
     * Addition information receives from payment network.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "additionalData" })
    @Type(() => AdditionalData)
    additionalData?: AdditionalData;

    /**
     * Indicates if address provided matches the billing address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "addressVerificationResult" })
    addressVerificationResult?: AddressVerificationResult;

    /**
     * Codifies authentication of the address related to the payment card account at the transaction location during the authorization phase of a payment transaction(e.g. Z = zip code match, A = address match).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "addressVerificationResultCode" })
    addressVerificationResultCode?: string;

    /**
     * Identifies the number assigned by MasterCard to each authorization message between a card acceptor and an issuer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "banknetReferenceNumber" })
    banknetReferenceNumber?: string;

    /**
     * Indicates if the card verification values (CVV/CV2) matches
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardVerificationResult" })
    cardVerificationResult?: CardVerificationResult;

    /**
     * Codifies the results of the cardholder authentication match test within the processor.  Authentication test is based on whether the MasterCard Card Verification Character (CVC) or the Visa Card Verification Value (CVV) presented with the transaction matches what the Firm has on file for the card account (e.g., M = CVV2 matched, N = CVV2 did not match).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardVerificationResultCode" })
    cardVerificationResultCode?: string;

    /**
     * Identifies a reference number generated at transaction time.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "debitTraceNumber" })
    debitTraceNumber?: string;

    /**
     * Provides the textual detail information of the issuer's authorization response code to a merchant when verifying the cardholder's email address to help authenticate transactions and prevent fraud. This is Amex only field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "emailVerificationResult" })
    emailVerificationResult?: EmailVerificationResult;

    /**
     * Codifies the issuer's authorization response code to a merchant when verifying the cardholder's email address to help authenticate transactions and prevent fraud.This is Amex only field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "emailVerificationResultCode" })
    emailVerificationResultCode?: string;

    /**
     * Masked Card Number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4CardNumber" })
    last4CardNumber?: string;

    /**
     * Account update information as returned by the network
     */
    @SpeakeasyMetadata()
    @Expose({ name: "networkAccountUpdater" })
    @Type(() => NetworkResponseAccountUpdater)
    networkAccountUpdater?: NetworkResponseAccountUpdater;

    /**
     * A unique identifier for the transaction returned by the issuer. For Mastercard, this includes the    BanknetReferenceNumber.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "networkTransactionId" })
    networkTransactionId?: string;

    /**
     * A unique identifier associated with a specific cardholder primary account number (PAN) used to link a payment account represented by that PAN to affiliated payment tokens. This 29 character identification number can be used in place of sensitive consumer identification fields, and transmitted across the payments ecosystem to facilitate consumer identification.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "paymentAccountReference" })
    paymentAccountReference?: string;

    /**
     * Codifies the issuer's authorization response code to a merchant when verifying the cardholder's billing telephone number to help authenticate transactions and prevent fraud. This is Amex only field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phoneVerificationResult" })
    phoneVerificationResult?: PhoneVerificationResult;

    /**
     * Provides the textual detail information of the issuer's authorization response code to a merchant when verifying the cardholder's billing telephone number to help authenticate transactions and prevent fraud.This is Amex only field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phoneVerificationResultCode" })
    phoneVerificationResultCode?: string;

    /**
     * Indicates assurance level associated with the token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenAssuranceScore" })
    tokenAssuranceScore?: string;

    /**
     * Identifier for the merchant given by the token requestor
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenRequestorIdentifier" })
    tokenRequestorIdentifier?: string;

    /**
     * Indicates the status of the token. For Visa - A= Active for payment, I = Inactive for payment, S= Temporarily suspended for payments, D = Permanently deactivated for payments.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenStatus" })
    tokenStatus?: string;
}
