/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains response information related to Account Updater request
 */
export enum AccountStatus {
    A = "A",
    C = "C",
    E = "E",
    Q = "Q",
}

/**
 * Account update information as returned by the network
 */
export class NetworkResponseAccountUpdater extends SpeakeasyBase {
    /**
     * Contains response information related to Account Updater request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "accountStatus" })
    accountStatus?: AccountStatus;

    /**
     * Network provided error or reason code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "networkResponseCode" })
    networkResponseCode?: string;

    /**
     * Indicates if replacement of any information has occurred
     */
    @SpeakeasyMetadata()
    @Expose({ name: "replacementCode" })
    replacementCode?: boolean;
}
