/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Contains expiry for masked PAN if received from network
 */
export class PanExpiryOutput extends SpeakeasyBase {}
