/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Identifies how accountholders  initiated debits to their accounts .
 */
export enum PaymentType {
    Web = "WEB",
    Tel = "TEL",
    Recurring = "RECURRING",
}
