/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Codifies a high level classification associated with the card account that could indicate how the issuer account is funded or used, e.g. Debit, Credit, Prepaid, Single Use.
 */
export enum PaymentBrandCardTypeCode {
    CreditCard = "CREDIT_CARD",
    DebitCard = "DEBIT_CARD",
    PrepaidCard = "PREPAID_CARD",
    ChargeCard = "CHARGE_CARD",
    DeferredDebit = "DEFERRED_DEBIT",
    NonMastercard = "NON_MASTERCARD",
}
