/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Payment capture information for multi capture order
 */
export class PaymentCapture extends SpeakeasyBase {
    /**
     * Specifies the monetary value of the transaction performed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * Identifies a unique occurrence of a payment settlement request when the authorization is complete and the transaction is ready for settlement. The transaction can no longer be edited but can be voided.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "captureId" })
    captureId?: string;

    /**
     * Capture amount available to be refunded
     */
    @SpeakeasyMetadata()
    @Expose({ name: "captureRemainingRefundableAmount" })
    captureRemainingRefundableAmount?: number;

    /**
     * Codifies the point in the payment transaction flow of the transaction. For example, a typical transaction is authorized then captured for clearing and settlement; closed is when the transaction is ready for clearing and completed when the transaction is sent to the payment network for clearing.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transactionStatusCode" })
    transactionStatusCode?: string;
}
