/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseStatus } from "./responsestatus";
import { TokenProvider } from "./tokenprovider";
import { Expose } from "class-transformer";

/**
 * Token Information for the payment transaction
 */
export class PaymentToken extends SpeakeasyBase {
    /**
     * The label given to the state of a response to a request submitted by a consumer through the Firm's Application Program Interface (API) that matches a test case. Valid Values: ERROR,SUCCESS, DENIED
     */
    @SpeakeasyMetadata()
    @Expose({ name: "responseStatus" })
    responseStatus?: ResponseStatus;

    /**
     * The token number is a secure surrogate value generated for an account number in a payment transaction. The token is substituted for the card number or primary account number (PAN), Demand Deposit Account (DDA) Number or other payment account and is used to process and identify transactions originating from that account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenNumber" })
    tokenNumber?: string;

    /**
     * The label given to a provider who creates the digital token for cards.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenProvider" })
    tokenProvider?: TokenProvider;

    /**
     * Short explanation of response Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenServiceResponseCode" })
    tokenServiceResponseCode?: string;

    /**
     * Long explanation of response Message received from token service
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenServiceResponseMessage" })
    tokenServiceResponseMessage?: string;
}
