/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
 */
export class Phone extends SpeakeasyBase {
    /**
     * The telephone dialing prefix for a member country in the International Telecommunication Union (ITU) that is defined by the ITU-T E.164 standard. The code is a combination of one, two or three digits identifying a specific country, countries in an integrated numbering plan, or a specific geographic area.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "countryCode" })
    countryCode?: number;

    /**
     * A locator whose value identifies the formatted numeric address for routing voice or data communications via telephony, to reach a party. NOTE: Telephone number formats may vary; this field can include domestic and international telephone numbers.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phoneNumber" })
    phoneNumber: string;
}
