/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The label for primary transactions processing network through which card's (Debit or credit) account transactions are processed.
 */
export enum PreferredPaymentNetworkName {
    StarPinless = "STAR_PINLESS",
    PulsePinless = "PULSE_PINLESS",
    NycePinless = "NYCE_PINLESS",
    AccelPinless = "ACCEL_PINLESS",
}
