/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Codifies the point in the recurring transaction by the consumer to the merchant for products or services.
 */
export enum RecurringSequence {
    First = "FIRST",
    Subsequent = "SUBSEQUENT",
}
