/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The authentication object allows you to opt in to additional security features specific for refund
 */
export class RefundAuthentication extends SpeakeasyBase {
    /**
     * Describes the Electronic Commerce Indicator used in cardholder authentication on a network token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "electronicCommerceIndicator" })
    electronicCommerceIndicator?: string;

    /**
     * Contains authentication value received from Payment Networks for network token transactions
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tokenAuthenticationValue" })
    tokenAuthenticationValue?: string;
}
