/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Ach } from "./ach";
import { RefundCard } from "./refundcardoutput";
import { TransactionReference } from "./transactionreference";
import { Expose, Type } from "class-transformer";

/**
 * Object with one of the payment method type applicable for refund processing
 */
export class RefundPaymentMethodType extends SpeakeasyBase {
    /**
     * Object for ACH (Automated Clearing House) payment method which occurs whenever someone instructs the ACH network to ?push? money from their account to someone else's. This is mostly used in USA.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => Ach)
    ach?: Ach;

    /**
     * Card payment instrument for refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => RefundCard)
    card?: RefundCard;

    /**
     * Object for refund transaction reference
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transactionReference" })
    @Type(() => TransactionReference)
    transactionReference?: TransactionReference;
}
