/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The label given to the state of a response to a request submitted by a consumer through the Firm's Application Program Interface (API) that matches a test case. Valid Values: ERROR,SUCCESS, DENIED
 */
export enum ResponseStatus {
    Success = "SUCCESS",
    Denied = "DENIED",
    Error = "ERROR",
}
