/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Level3 } from "./level3";
import { Expose, Type } from "class-transformer";

/**
 * Retail inductry specific attributes.
 */
export class RetailAddenda extends SpeakeasyBase {
    /**
     * Specifies the monetary value paid by the consumer over and above the payment due for service.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gratuityAmount" })
    gratuityAmount?: number;

    /**
     * Indicates whether tax should be collected for the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isTaxable" })
    isTaxable?: boolean;

    /**
     * Level 3 data provides commercial shoppers with additional information about purchases on their card statements.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "level3" })
    @Type(() => Level3)
    level3?: Level3;

    /**
     * Designates the year, month, and day the request to purchase a service(s) or good(s) took place.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "orderDate" })
    orderDate?: string;

    /**
     * The Purchase Order Number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "purchaseOrderNumber" })
    purchaseOrderNumber?: string;

    /**
     * Specifies the monetary value amount assessed to the transaction identified as Tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "taxAmount" })
    taxAmount?: number;
}
