/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardType } from "./cardtype";
import { Expose } from "class-transformer";

/**
 * Object containing Risk Element information
 */
export class RiskElement extends SpeakeasyBase {
    /**
     * Indicates if the device's application software, used to communicate between users of the Internet's World Wide Web, allows Adobe flash.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "browserAdobeFlashEnabled" })
    browserAdobeFlashEnabled?: boolean;

    /**
     * Indicates if the device's application software, used to communicate between users of the Internet's World Wide Web, allows cookies.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "browserCookiesEnabled" })
    browserCookiesEnabled?: boolean;

    /**
     * Indicates if the device's application software, used to communicate between users of the Internet's World Wide Web, allows javascript.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "browserJavaScriptEnabled" })
    browserJavaScriptEnabled?: boolean;

    /**
     * Abbreviation of card name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cardType" })
    cardType?: CardType;

    /**
     * Uniquely represents a firm-recognized geopolitical area, including the ISO 3166 alpha 2-character country codes and other firm-created country codes. In this context, this is the country code associated with browser.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceBrowserCountry" })
    deviceBrowserCountry?: string;

    /**
     * Codifies the method of communication, either spoken or written, consisting of the use of words in a structured and conventional way. The gold (master) set of values is defined by the International Standards Organization in ISO standard 639-3. In this context, this is the the language the device owner has set in the device settings.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceBrowserLanguage" })
    deviceBrowserLanguage?: string;

    /**
     * Codifies the country, a geographic area, that is recognized as an independent political unit in world affairs where the point of sale device was used for a transaction. Null value indicates country code is not provided.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceCountry" })
    deviceCountry?: string;

    /**
     * Identifies a unique occurrence of an electronic device (and the software) used by the customer to communicate with the Firm or a third party to receive, store, process or send digital information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceLayers" })
    deviceLayers?: string;

    /**
     * Represents a unique code assigned by the firm for a geographical area that observes a uniform standard time for legal, commercial, and social purposes. In this context, this is the local time the device owner has set in the device settings.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceLocalTimeZone" })
    deviceLocalTimeZone?: string;

    /**
     * Codifies the categorization of the internet network using the Internet Protocol (IP) Address associated with the party (consumer). This category is assigned by the fraud engine based on the IP address/domain.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceNetworkType" })
    deviceNetworkType?: string;

    /**
     * Indicates if a device uses a proxy server as an intermediary between an endpoint device, such as a computer or mobile device, and the server from which a user or client is making a purchase.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceProxyServer" })
    deviceProxyServer?: boolean;

    /**
     * Codifies a geographic area represented by one or more Countries, States or Provinces. Country, State or Province identifies a geographic area that represents a Firm recognized geopolitical unit. In this context, this is the region associated to the Device Location.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceRegion" })
    deviceRegion?: string;

    /**
     * Indicate if the device placing the order is enabled to use PC Remote software.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceRemotelyControlCapability" })
    deviceRemotelyControlCapability?: boolean;

    /**
     * Designates the current hour (hh), minute (mm), seconds (ss) and date on the eletronic instrument used by a consumer for a payment authorization during the fraud analysis. This may differ from the actual current time if changed by the device owner.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceTimestamp" })
    deviceTimestamp?: string;

    /**
     * Indicate if the device placing the order voice activated (related to mobile devices).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceVoiceControlled" })
    deviceVoiceControlled?: boolean;

    /**
     * Indicate if the device placing the order has capability to connect to internet wirelessly.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deviceWirelessCapability" })
    deviceWirelessCapability?: boolean;

    /**
     * The label given to the type of electronic device that can receive, store, process or send digital information that can be used to communicate with a web page.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "digitalDeviceType" })
    digitalDeviceType?: string;

    /**
     * Enumerates the quantity of records in a data object that is processed or transmitted. In this context, this is the number of cards associated with transaction that the fraud system has recorded.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fourteenDaysCardRecordCount" })
    fourteenDaysCardRecordCount?: number;

    /**
     * Enumerates the quantity of records in a data object that is processed or transmitted. In this context, this is the record count of the email associated with the transaction that the fraud system has recorded.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fourteenDaysDeviceRecordCount" })
    fourteenDaysDeviceRecordCount?: number;

    /**
     * Enumerates the quantity of records in a data object that is processed or transmitted. In this context, this is the record count of the devices associated with the transaction that the fraud system has recorded.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fourteenDaysEmailRecordCount" })
    fourteenDaysEmailRecordCount?: number;

    /**
     * Enumerates the occurrences of any transaction within a given period. In this context, this represent how many times the persona has been seen for the merchant in last 14 days.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fourteenDaysTransactionCount" })
    fourteenDaysTransactionCount?: number;

    /**
     * Identifies a unique occurrence of a transaction. In this context, this is the fraud evaluator provided transaction id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudEvaluatorTransactionId" })
    fraudEvaluatorTransactionId?: string;

    /**
     * Identifies a unique occurrence of an electronic device (and the software) used by the customer to communicate with the Firm or a third party to receive, store, process or send digital information. In this context, this identifier consists of the 5 device layers representing the operating system, browser, JavaScript settings, cookie setting and flash settings.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hashedDigitalDeviceFingerprintIdentifier" })
    hashedDigitalDeviceFingerprintIdentifier?: string;

    /**
     * The portion of a party's address that is the encoded representation of a geographic area representing a country. Tn this context, this represents the country with the highest level of known e-commerce risk, as determined by the US State Department, that has been associated with a particular persona within the last 14 days.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "highestRiskCountry" })
    highestRiskCountry?: string;

    /**
     * Codifies a geographic area represented by one or more Countries, States or Provinces. Country, State or Province identifies a geographic area that represents a Firm recognized geopolitical unit. In this context, this is the region which represents the highest level of known e-commerce risk, as determined by the US State Department, that has been associated with a particular persona within the last 14 days.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "highestRiskRegion" })
    highestRiskRegion?: string;

    /**
     * Indicate if the device placing the order a mobile device.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mobileDevice" })
    mobileDevice?: boolean;

    /**
     * Indicates the Kaptcha session identifier generated by the fraud engine during checkout is validated and matches the session identifier received on the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sessionMatchIndicator" })
    sessionMatchIndicator?: boolean;

    /**
     * Enumerates the occurrences of any transaction within a given period. In this context, this represent how many times the persona has been seen for the merchant in last 6 hours.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sixHoursTransactionCount" })
    sixHoursTransactionCount?: number;
}
