/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Object containing Risk Decision information.
 */
export class RiskDecision extends SpeakeasyBase {
    /**
     * The moniker given to the alert rule used to identify potential fraud online. (e.g. 200Billpay, 300ACH, QPRT Quickpay V005)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "digitalAlertRuleName" })
    digitalAlertRuleName?: string;

    /**
     * Codifies the success or failure of a request to the fraud engine to assign a risk score to a payment transaction. This request is done prior to the authorization.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudRiskResponse" })
    fraudRiskResponse?: string;

    /**
     * industryType
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudRiskScore" })
    fraudRiskScore?: string;

    /**
     * Codifies the next step of the fraud analysis based on the risk rule result as defined by the merchant.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudRuleAction" })
    fraudRuleAction?: string;

    /**
     * Codifies the status of card at time of suspected fraud. Note: Used in conjunction with the Fraud Method Code field. Contains the first character the 2-character alphanumeric Fraud Type entered in the Code1 field of the Work Suspect Fraud screen. Code used to further define an account status. Specifically, the fraud type codes defined by credit card associations. Commonly known as Fraud Type 1 Code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudStatus" })
    fraudStatus?: string;

    /**
     * The label for the status of card at time of suspected fraud. Note: Used in conjunction with the Fraud Method Code field. Contains the first character the 2-character alphanumeric Fraud Type entered in the Code1 field of the Work Suspect Fraud screen. Code used to further define an account status. Specifically, the fraud type codes defined by credit card associations. Commonly known as Fraud Type 1 Code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraudStatusDescription" })
    fraudStatusDescription?: string;
}
