/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Phone } from "./phone";
import { Expose, Type } from "class-transformer";

/**
 * Object containing information about the recipients
 */
export class ShipTo extends SpeakeasyBase {
    /**
     * Optional value for merchants to provide for a transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * Name of accountholder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fullName" })
    fullName?: string;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mobile" })
    @Type(() => Phone)
    mobile?: Phone;

    /**
     * Phone number in ITU-T E.164 format. Country code and phone number (subscriber number) are mandatory values
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    @Type(() => Phone)
    phone?: Phone;

    /**
     * Address Object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingAddress" })
    @Type(() => Address)
    shippingAddress?: Address;

    /**
     * Description of shipping or delivery method
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shippingDescription" })
    shippingDescription?: string;
}
