/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The label given to a provider who creates the digital token for cards.
 */
export enum TokenProvider {
    Network = "NETWORK",
    Safetech = "SAFETECH",
}
