/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Object for refund transaction reference
 */
export class TransactionReference extends SpeakeasyBase {
    /**
     * Reference to an existing payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transactionReferenceId" })
    transactionReferenceId: string;
}
