/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum TransactionRoutingOverrideList {
    Stone = "STONE",
    Cielo = "CIELO",
    Getnet = "GETNET",
    Redecard = "REDECARD",
}
