/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { VerificationACH, VerificationACHOutput } from "./verificationach";
import { VerificationCard, VerificationCardOutput } from "./verificationcard";
import { Expose, Type } from "class-transformer";

/**
 * Object with one of the payment method type applicable for verification processing
 */
export class VerificationPaymentMethodTypeOutput extends SpeakeasyBase {
    /**
     * Verification of ACH account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => VerificationACHOutput)
    ach?: VerificationACHOutput;

    /**
     * Card payment instrument for card verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => VerificationCardOutput)
    card?: VerificationCardOutput;
}

/**
 * Object with one of the payment method type applicable for verification processing
 */
export class VerificationPaymentMethodType extends SpeakeasyBase {
    /**
     * Verification of ACH account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => VerificationACH)
    ach?: VerificationACH;

    /**
     * Card payment instrument for card verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => VerificationCard)
    card?: VerificationCard;
}
