/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { VerificationACHInput, VerificationACHOutput } from "./verificationach";
import { VerificationCardInput, VerificationCardOutput } from "./verificationcard";
import { Expose, Type } from "class-transformer";

/**
 * Object with one of the payment method type applicable for verification processing
 */
export class VerificationPaymentMethodTypeInput extends SpeakeasyBase {
    /**
     * Verification of ACH account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => VerificationACHInput)
    ach?: VerificationACHInput;

    /**
     * Card payment instrument for card verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => VerificationCardInput)
    card?: VerificationCardInput;
}

/**
 * Object with one of the payment method type applicable for verification processing
 */
export class VerificationPaymentMethodTypeOutput extends SpeakeasyBase {
    /**
     * Verification of ACH account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => VerificationACHOutput)
    ach?: VerificationACHOutput;

    /**
     * Card payment instrument for card verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => VerificationCardOutput)
    card?: VerificationCardOutput;
}
