/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { VerificationACH } from "./verificationachoutput";
import { VerificationCard } from "./verificationcardoutput";
import { Expose, Type } from "class-transformer";

/**
 * Object with one of the payment method type applicable for verification processing
 */
export class VerificationPaymentMethodType extends SpeakeasyBase {
    /**
     * Verification of ACH account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ach" })
    @Type(() => VerificationACH)
    ach?: VerificationACH;

    /**
     * Card payment instrument for card verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => VerificationCard)
    card?: VerificationCard;
}
