/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains value returned in the transaction status field of the Payer Authentication Response (PARes) message from the card Issuer's Access Control Server (ACS). Y=Authentication successful ; N=Authentication failed ; U=Authentication unavailable ; A=Attempted authentication
 */
export enum Version1ThreeDSPAResStatus {
    Y = "Y",
    N = "N",
    U = "U",
    A = "A",
}

/**
 * Contains value returned in the 'enrolled' field of the Verify Enrollment Response (VERes) message from the card scheme's Directory Server. Y=Authentication successful;  N=Authentication failed; U=Authentication unavailable;  A=Attempted authentication
 */
export enum Version1ThreeDSVEResEnrolled {
    Y = "Y",
    N = "N",
    U = "U",
    A = "A",
}

/**
 * Contains information about payer authentication using 3-D Secure authentication version 1
 */
export class Version1 extends SpeakeasyBase {
    /**
     * Contains value returned in the transaction status field of the Payer Authentication Response (PARes) message from the card Issuer's Access Control Server (ACS). Y=Authentication successful ; N=Authentication failed ; U=Authentication unavailable ; A=Attempted authentication
     */
    @SpeakeasyMetadata()
    @Expose({ name: "threeDSPAResStatus" })
    threeDSPAResStatus?: Version1ThreeDSPAResStatus;

    /**
     * Contains value returned in the 'enrolled' field of the Verify Enrollment Response (VERes) message from the card scheme's Directory Server. Y=Authentication successful;  N=Authentication failed; U=Authentication unavailable;  A=Attempted authentication
     */
    @SpeakeasyMetadata()
    @Expose({ name: "threeDSVEResEnrolled" })
    threeDSVEResEnrolled?: Version1ThreeDSVEResEnrolled;
}
