/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose } from "class-transformer";

/**
 * Object containing information about transaction validation
 */
export class ValidationMessage extends Error {
    /**
     * Short informative code about error
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * The moniker given to the module or program where the error generated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "entity" })
    entity?: string;

    /**
     * Long informative message about error
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;

    constructor(err?: ValidationMessage) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ValidationMessage";
        Object.setPrototypeOf(this, ValidationMessage.prototype);
    }
}
