/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Object containing information about transaction validation
 */
export class ValidationMessage extends SpeakeasyBase {
    /**
     * Short informative code about error
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * The moniker given to the module or program where the error generated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "entity" })
    entity?: string;

    /**
     * Long informative message about error
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}
